'use client'

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'id'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'login.title': 'Salomo Partners',
    'login.subtitle': 'AI-Powered Legal Workspace',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.remember': 'Remember me',
    'login.forgot': 'Forgot password?',
    'login.button': 'Sign In',
    'login.noAccount': "Don't have an account?",
    'login.register': 'Register',

    'nav.dashboard': 'Dashboard',
    'nav.cases': 'Cases',
    'nav.clients': 'Clients',
    'nav.documents': 'Documents',
    'nav.calendar': 'Calendar',
    'nav.settings': 'Settings',
    'nav.logout': 'Sign Out',
    'nav.aiAssistant': 'AI Legal Chat',
    'nav.audioTranscribe': 'Audio Transcribe',
    'nav.lawCompare': 'Law Comparator',
    'nav.ocrTool': 'Doc Scanner',
    'nav.meeting': 'Meeting Room',
    'nav.aiTools': 'AI TOOLS',
    'nav.management': 'MANAGEMENT',
    'nav.workspace': 'WORKSPACE',

    'dashboard.welcome': 'Welcome back',
    'dashboard.overview': 'Here\'s your AI-powered practice overview',
    'dashboard.activeCases': 'Active Cases',
    'dashboard.totalClients': 'Total Clients',
    'dashboard.pendingTasks': 'Pending Tasks',
    'dashboard.recentCases': 'Recent Cases',
    'dashboard.upcomingEvents': 'Upcoming Events',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.caseDistribution': 'Case Distribution',
    'dashboard.viewAll': 'View All',
    'dashboard.aiChat': 'AI Legal Assistant',
    'dashboard.aiChatPlaceholder': 'Ask about Indonesian law, regulations, legal procedures...',
    'dashboard.aiChatWelcome': 'Hello! I\'m your AI Legal Assistant specialized in Indonesian law. Ask me about legal regulations, procedures, articles, or any legal matter.',
    'dashboard.aiSend': 'Send',
    'dashboard.quickActions': 'Quick AI Actions',

    'cases.title': 'Case Management',
    'cases.subtitle': 'Manage and track all your legal cases',
    'cases.new': 'New Case',
    'cases.search': 'Search cases...',
    'cases.filter': 'Filter',
    'cases.caseNumber': 'Case No.',
    'cases.caseName': 'Case Name',
    'cases.client': 'Client',
    'cases.type': 'Type',
    'cases.status': 'Status',
    'cases.priority': 'Priority',
    'cases.assignee': 'Assignee',
    'cases.date': 'Date',
    'cases.actions': 'Actions',
    'cases.active': 'Active',
    'cases.pending': 'Pending',
    'cases.closed': 'Closed',
    'cases.review': 'In Review',
    'cases.high': 'High',
    'cases.medium': 'Medium',
    'cases.low': 'Low',
    'cases.view': 'View',
    'cases.edit': 'Edit',
    'cases.delete': 'Delete',
    'cases.all': 'All Cases',
    'cases.details': 'Case Details',
    'cases.description': 'Description',
    'cases.notes': 'Notes',
    'cases.timeline': 'Timeline',
    'cases.addNote': 'Add Note',
    'cases.save': 'Save',
    'cases.cancel': 'Cancel',
    'cases.close': 'Close',

    'clients.title': 'Client Management',
    'clients.subtitle': 'Manage your client relationships',
    'clients.new': 'New Client',
    'clients.search': 'Search clients...',
    'clients.name': 'Name',
    'clients.email': 'Email',
    'clients.phone': 'Phone',
    'clients.company': 'Company',
    'clients.cases': 'Cases',
    'clients.status': 'Status',
    'clients.joined': 'Joined',
    'clients.active': 'Active',
    'clients.inactive': 'Inactive',

    'docs.title': 'Document Management',
    'docs.subtitle': 'Store and manage all legal documents',
    'docs.upload': 'Upload Document',
    'docs.search': 'Search documents...',
    'docs.name': 'Document Name',
    'docs.type': 'Type',
    'docs.case': 'Related Case',
    'docs.size': 'Size',
    'docs.modified': 'Last Modified',
    'docs.download': 'Download',
    'docs.preview': 'Preview',
    'docs.print': 'Print',
    'docs.contract': 'Contract',
    'docs.pleading': 'Pleading',
    'docs.correspondence': 'Correspondence',
    'docs.evidence': 'Evidence',
    'docs.memo': 'Memo',

    'calendar.title': 'Calendar',
    'calendar.subtitle': 'Schedule and manage appointments',
    'calendar.newEvent': 'New Event',
    'calendar.today': 'Today',
    'calendar.month': 'Month',
    'calendar.week': 'Week',
    'calendar.day': 'Day',
    'calendar.hearing': 'Hearing',
    'calendar.meeting': 'Meeting',
    'calendar.deadline': 'Deadline',
    'calendar.consultation': 'Consultation',
    'calendar.upcoming': 'Upcoming Events',

    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your account and preferences',
    'settings.profile': 'Profile',
    'settings.appearance': 'Appearance',
    'settings.notifications': 'Notifications',
    'settings.security': 'Security',
    'settings.language': 'Language',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.system': 'System',
    'settings.fullName': 'Full Name',
    'settings.email': 'Email',
    'settings.role': 'Role',
    'settings.firm': 'Firm Name',
    'settings.save': 'Save Changes',
    'settings.emailNotif': 'Email Notifications',
    'settings.pushNotif': 'Push Notifications',
    'settings.caseUpdates': 'Case Updates',
    'settings.deadlineReminders': 'Deadline Reminders',
    'settings.newMessages': 'New Messages',
    'settings.changePassword': 'Change Password',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm Password',
    'settings.twoFactor': 'Two-Factor Authentication',
    'settings.twoFactorDesc': 'Add an extra layer of security to your account',
    'settings.enable': 'Enable',
    'settings.disable': 'Disable',
    'settings.aiConfig': 'AI Configuration',
    'settings.aiConfigDesc': 'Configure your Gemini API key to enable AI features',
    'settings.keyConfigured': 'API key is configured',
    'settings.keyNotConfigured': 'No API key configured',
    'settings.keyStoredLocally': 'Your API key is stored locally in your browser and never sent to our servers.',
    'settings.keySaved': 'Saved!',
    'settings.saveKey': 'Save Key',
    'settings.removeKey': 'Remove',
    'settings.howToGetKey': 'How to get an API key',
    'settings.step1': 'Visit Google AI Studio',
    'settings.step2': 'Sign in with your Google account',
    'settings.step3': 'Click "Create API Key" to generate a new key',
    'settings.step4': 'Copy and paste the key above',
    'settings.openAIStudio': 'Open Google AI Studio',
    'settings.aiNote1': 'AI features use Gemini 2.0 Flash for fast, cost-effective responses.',
    'settings.aiNote2': 'Without an API key, AI tools will use demo/mock responses.',

    'audio.title': 'AI Audio Transcription',
    'audio.subtitle': 'Transform audio recordings into accurate text with AI',
    'audio.upload': 'Upload Audio',
    'audio.record': 'Record Audio',
    'audio.stop': 'Stop Recording',
    'audio.transcribe': 'Transcribe with AI',
    'audio.rawText': 'Raw Transcription',
    'audio.summary': 'AI Summary',
    'audio.recording': 'Recording...',
    'audio.processing': 'Processing with AI...',
    'audio.dragDrop': 'Drag & drop audio file or click to browse',
    'audio.formats': 'Supports MP3, WAV, M4A, WEBM',
    'audio.noTranscription': 'No transcription yet. Upload or record audio to get started.',
    'audio.copyText': 'Copy Text',
    'audio.export': 'Export',
    'audio.save': 'Save to Documents',

    'lawCompare.title': 'AI Law Article Comparator',
    'lawCompare.subtitle': 'Compare and analyze Indonesian law articles side by side',
    'lawCompare.addArticle': 'Add Article',
    'lawCompare.compare': 'Compare with AI',
    'lawCompare.article': 'Article',
    'lawCompare.law': 'Law / Regulation',
    'lawCompare.content': 'Article Content',
    'lawCompare.analysis': 'AI Analysis',
    'lawCompare.similarities': 'Similarities',
    'lawCompare.differences': 'Differences',
    'lawCompare.recommendation': 'Recommendation',
    'lawCompare.placeholder': 'Enter or paste the article text...',
    'lawCompare.lawPlaceholder': 'e.g., UU No. 13 Tahun 2003',

    'ocr.title': 'AI Document Scanner',
    'ocr.subtitle': 'Extract text from images and PDF files with AI',
    'ocr.upload': 'Upload File',
    'ocr.scan': 'Scan with AI',
    'ocr.result': 'Extracted Text',
    'ocr.dragDrop': 'Drag & drop image or PDF file',
    'ocr.formats': 'Supports JPG, PNG, PDF',
    'ocr.copy': 'Copy Text',
    'ocr.save': 'Save to Documents',
    'ocr.noResult': 'No scan result yet. Upload a file to get started.',

    'meeting.title': 'Meeting Room',
    'meeting.subtitle': 'Video conference with your team',
    'meeting.new': 'New Meeting',
    'meeting.join': 'Join Meeting',
    'meeting.schedule': 'Schedule Meeting',
    'meeting.roomId': 'Room ID',
    'meeting.start': 'Start Meeting',
    'meeting.end': 'End Meeting',
    'meeting.mute': 'Mute',
    'meeting.unmute': 'Unmute',
    'meeting.camera': 'Camera',
    'meeting.share': 'Share Screen',
    'meeting.chat': 'Chat',
    'meeting.participants': 'Participants',
    'meeting.leave': 'Leave Meeting',
    'meeting.waiting': 'Waiting for participants...',
    'meeting.copyLink': 'Copy Meeting Link',
    'meeting.scheduled': 'Scheduled Meetings',

    'common.search': 'Search',
    'common.add': 'Add',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.loading': 'Loading...',
    'common.noData': 'No data available',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.actions': 'Actions',
    'common.showing': 'Showing',
    'common.of': 'of',
    'common.entries': 'entries',
    'common.print': 'Print',
  },
  id: {
    'login.title': 'Salomo Partners',
    'login.subtitle': 'Ruang Kerja Hukum Berbasis AI',
    'login.email': 'Alamat Email',
    'login.password': 'Kata Sandi',
    'login.remember': 'Ingat saya',
    'login.forgot': 'Lupa kata sandi?',
    'login.button': 'Masuk Sistem',
    'login.noAccount': 'Belum punya akun?',
    'login.register': 'Daftar',

    'nav.dashboard': 'Dasbor',
    'nav.cases': 'Perkara',
    'nav.clients': 'Klien',
    'nav.documents': 'Dokumen',
    'nav.calendar': 'Kalender',
    'nav.settings': 'Pengaturan',
    'nav.logout': 'Keluar',
    'nav.aiAssistant': 'AI Chat Hukum',
    'nav.audioTranscribe': 'Transkripsi Audio',
    'nav.lawCompare': 'Komparator Pasal',
    'nav.ocrTool': 'Pemindai Dokumen',
    'nav.meeting': 'Ruang Meeting',
    'nav.aiTools': 'ALAT AI',
    'nav.management': 'MANAJEMEN',
    'nav.workspace': 'RUANG KERJA',

    'dashboard.welcome': 'Selamat datang kembali',
    'dashboard.overview': 'Ringkasan praktik hukum Anda berbasis AI',
    'dashboard.activeCases': 'Perkara Aktif',
    'dashboard.totalClients': 'Total Klien',
    'dashboard.pendingTasks': 'Tugas Tertunda',
    'dashboard.recentCases': 'Perkara Terbaru',
    'dashboard.upcomingEvents': 'Jadwal Mendatang',
    'dashboard.recentActivity': 'Aktivitas Terbaru',
    'dashboard.caseDistribution': 'Distribusi Perkara',
    'dashboard.viewAll': 'Lihat Semua',
    'dashboard.aiChat': 'Asisten AI Hukum',
    'dashboard.aiChatPlaceholder': 'Tanya tentang hukum Indonesia, regulasi, prosedur hukum...',
    'dashboard.aiChatWelcome': 'Halo! Saya asisten AI hukum yang mengkhususkan pada hukum Indonesia. Tanyakan tentang regulasi, prosedur, pasal, atau masalah hukum apapun.',
    'dashboard.aiSend': 'Kirim',
    'dashboard.quickActions': 'Aksi Cepat AI',

    'cases.title': 'Manajemen Perkara',
    'cases.subtitle': 'Kelola dan lacak semua perkara hukum',
    'cases.new': 'Perkara Baru',
    'cases.search': 'Cari perkara...',
    'cases.filter': 'Filter',
    'cases.caseNumber': 'No. Perkara',
    'cases.caseName': 'Nama Perkara',
    'cases.client': 'Klien',
    'cases.type': 'Tipe',
    'cases.status': 'Status',
    'cases.priority': 'Prioritas',
    'cases.assignee': 'Penanggung Jawab',
    'cases.date': 'Tanggal',
    'cases.actions': 'Aksi',
    'cases.active': 'Aktif',
    'cases.pending': 'Tertunda',
    'cases.closed': 'Ditutup',
    'cases.review': 'Dalam Peninjauan',
    'cases.high': 'Tinggi',
    'cases.medium': 'Sedang',
    'cases.low': 'Rendah',
    'cases.view': 'Lihat',
    'cases.edit': 'Ubah',
    'cases.delete': 'Hapus',
    'cases.all': 'Semua Perkara',
    'cases.details': 'Detail Perkara',
    'cases.description': 'Deskripsi',
    'cases.notes': 'Catatan',
    'cases.timeline': 'Linimasa',
    'cases.addNote': 'Tambah Catatan',
    'cases.save': 'Simpan',
    'cases.cancel': 'Batal',
    'cases.close': 'Tutup',

    'clients.title': 'Manajemen Klien',
    'clients.subtitle': 'Kelola hubungan klien Anda',
    'clients.new': 'Klien Baru',
    'clients.search': 'Cari klien...',
    'clients.name': 'Nama',
    'clients.email': 'Email',
    'clients.phone': 'Telepon',
    'clients.company': 'Perusahaan',
    'clients.cases': 'Perkara',
    'clients.status': 'Status',
    'clients.joined': 'Bergabung',
    'clients.active': 'Aktif',
    'clients.inactive': 'Tidak Aktif',

    'docs.title': 'Manajemen Dokumen',
    'docs.subtitle': 'Simpan dan kelola semua dokumen hukum',
    'docs.upload': 'Unggah Dokumen',
    'docs.search': 'Cari dokumen...',
    'docs.name': 'Nama Dokumen',
    'docs.type': 'Tipe',
    'docs.case': 'Perkara Terkait',
    'docs.size': 'Ukuran',
    'docs.modified': 'Terakhir Diubah',
    'docs.download': 'Unduh',
    'docs.preview': 'Pratinjau',
    'docs.print': 'Cetak',
    'docs.contract': 'Kontrak',
    'docs.pleading': 'Pembelaan',
    'docs.correspondence': 'Korespondensi',
    'docs.evidence': 'Bukti',
    'docs.memo': 'Memo',

    'calendar.title': 'Kalender',
    'calendar.subtitle': 'Jadwalkan dan kelola pertemuan',
    'calendar.newEvent': 'Acara Baru',
    'calendar.today': 'Hari Ini',
    'calendar.month': 'Bulan',
    'calendar.week': 'Minggu',
    'calendar.day': 'Hari',
    'calendar.hearing': 'Sidang',
    'calendar.meeting': 'Rapat',
    'calendar.deadline': 'Tenggat',
    'calendar.consultation': 'Konsultasi',
    'calendar.upcoming': 'Jadwal Mendatang',

    'settings.title': 'Pengaturan',
    'settings.subtitle': 'Kelola akun dan preferensi Anda',
    'settings.profile': 'Profil',
    'settings.appearance': 'Tampilan',
    'settings.notifications': 'Notifikasi',
    'settings.security': 'Keamanan',
    'settings.language': 'Bahasa',
    'settings.theme': 'Tema',
    'settings.light': 'Terang',
    'settings.dark': 'Gelap',
    'settings.system': 'Sistem',
    'settings.fullName': 'Nama Lengkap',
    'settings.email': 'Email',
    'settings.role': 'Jabatan',
    'settings.firm': 'Nama Firma',
    'settings.save': 'Simpan Perubahan',
    'settings.emailNotif': 'Notifikasi Email',
    'settings.pushNotif': 'Notifikasi Push',
    'settings.caseUpdates': 'Pembaruan Perkara',
    'settings.deadlineReminders': 'Pengingat Tenggat',
    'settings.newMessages': 'Pesan Baru',
    'settings.changePassword': 'Ubah Kata Sandi',
    'settings.currentPassword': 'Kata Sandi Saat Ini',
    'settings.newPassword': 'Kata Sandi Baru',
    'settings.confirmPassword': 'Konfirmasi Kata Sandi',
    'settings.twoFactor': 'Autentikasi Dua Faktor',
    'settings.twoFactorDesc': 'Tambahkan lapisan keamanan ekstra ke akun Anda',
    'settings.enable': 'Aktifkan',
    'settings.disable': 'Nonaktifkan',
    'settings.aiConfig': 'Konfigurasi AI',
    'settings.aiConfigDesc': 'Atur API key Gemini untuk mengaktifkan fitur AI',
    'settings.keyConfigured': 'API key sudah terkonfigurasi',
    'settings.keyNotConfigured': 'API key belum dikonfigurasi',
    'settings.keyStoredLocally': 'API key Anda disimpan secara lokal di browser dan tidak pernah dikirim ke server kami.',
    'settings.keySaved': 'Tersimpan!',
    'settings.saveKey': 'Simpan Key',
    'settings.removeKey': 'Hapus',
    'settings.howToGetKey': 'Cara mendapatkan API key',
    'settings.step1': 'Kunjungi Google AI Studio',
    'settings.step2': 'Masuk dengan akun Google Anda',
    'settings.step3': 'Klik "Create API Key" untuk membuat key baru',
    'settings.step4': 'Salin dan tempel key di atas',
    'settings.openAIStudio': 'Buka Google AI Studio',
    'settings.aiNote1': 'Fitur AI menggunakan Gemini 2.0 Flash untuk respons cepat dan hemat biaya.',
    'settings.aiNote2': 'Tanpa API key, alat AI akan menggunakan respons demo.',

    'audio.title': 'Transkripsi Audio AI',
    'audio.subtitle': 'Ubah rekaman audio menjadi teks akurat dengan AI',
    'audio.upload': 'Unggah Audio',
    'audio.record': 'Rekam Audio',
    'audio.stop': 'Hentikan Rekaman',
    'audio.transcribe': 'Transkripsi dengan AI',
    'audio.rawText': 'Transkripsi Mentah',
    'audio.summary': 'Ringkasan AI',
    'audio.recording': 'Merekam...',
    'audio.processing': 'Memproses dengan AI...',
    'audio.dragDrop': 'Seret & lepas file audio atau klik untuk mencari',
    'audio.formats': 'Mendukung MP3, WAV, M4A, WEBM',
    'audio.noTranscription': 'Belum ada transkripsi. Unggah atau rekam audio untuk memulai.',
    'audio.copyText': 'Salin Teks',
    'audio.export': 'Ekspor',
    'audio.save': 'Simpan ke Dokumen',

    'lawCompare.title': 'Komparator Pasal Hukum AI',
    'lawCompare.subtitle': 'Bandingkan dan analisis pasal hukum Indonesia secara berdampingan',
    'lawCompare.addArticle': 'Tambah Pasal',
    'lawCompare.compare': 'Bandingkan dengan AI',
    'lawCompare.article': 'Pasal',
    'lawCompare.law': 'Undang-Undang / Regulasi',
    'lawCompare.content': 'Isi Pasal',
    'lawCompare.analysis': 'Analisis AI',
    'lawCompare.similarities': 'Persamaan',
    'lawCompare.differences': 'Perbedaan',
    'lawCompare.recommendation': 'Rekomendasi',
    'lawCompare.placeholder': 'Masukkan atau tempel teks pasal...',
    'lawCompare.lawPlaceholder': 'cth: UU No. 13 Tahun 2003',

    'ocr.title': 'Pemindai Dokumen AI',
    'ocr.subtitle': 'Ekstrak teks dari gambar dan file PDF dengan AI',
    'ocr.upload': 'Unggah File',
    'ocr.scan': 'Pindai dengan AI',
    'ocr.result': 'Teks Hasil Ekstraksi',
    'ocr.dragDrop': 'Seret & lepas gambar atau file PDF',
    'ocr.formats': 'Mendukung JPG, PNG, PDF',
    'ocr.copy': 'Salin Teks',
    'ocr.save': 'Simpan ke Dokumen',
    'ocr.noResult': 'Belum ada hasil pemindaian. Unggah file untuk memulai.',

    'meeting.title': 'Ruang Meeting',
    'meeting.subtitle': 'Konferensi video dengan tim Anda',
    'meeting.new': 'Meeting Baru',
    'meeting.join': 'Gabung Meeting',
    'meeting.schedule': 'Jadwalkan Meeting',
    'meeting.roomId': 'ID Ruangan',
    'meeting.start': 'Mulai Meeting',
    'meeting.end': 'Akhiri Meeting',
    'meeting.mute': 'Bisukan',
    'meeting.unmute': 'Bunyikan',
    'meeting.camera': 'Kamera',
    'meeting.share': 'Bagikan Layar',
    'meeting.chat': 'Obrolan',
    'meeting.participants': 'Peserta',
    'meeting.leave': 'Keluar Meeting',
    'meeting.waiting': 'Menunggu peserta...',
    'meeting.copyLink': 'Salin Link Meeting',
    'meeting.scheduled': 'Meeting Terjadwal',

    'common.search': 'Cari',
    'common.add': 'Tambah',
    'common.edit': 'Ubah',
    'common.delete': 'Hapus',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.close': 'Tutup',
    'common.back': 'Kembali',
    'common.next': 'Selanjutnya',
    'common.previous': 'Sebelumnya',
    'common.loading': 'Memuat...',
    'common.noData': 'Tidak ada data',
    'common.confirm': 'Konfirmasi',
    'common.yes': 'Ya',
    'common.no': 'Tidak',
    'common.actions': 'Aksi',
    'common.showing': 'Menampilkan',
    'common.of': 'dari',
    'common.entries': 'entri',
    'common.print': 'Cetak',
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('id')

  useEffect(() => {
    const saved = localStorage.getItem('salomo-language') as Language
    if (saved && (saved === 'en' || saved === 'id')) {
      setLanguageState(saved)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('salomo-language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used within LanguageProvider')
  return context
}
